baseURL = "https://geospatial-community.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Brisbane geocommunity website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
coverImage = "images/site-feature-image.png"
# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlightisdng
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
